### ISSUE TITLE
Install check error - test_ddl_triggers and CDB_QueryTablesTest

### ISSUE THREAD

**Issue by sindile** [danseely/cartodb-install#1]
I have followed your steps and have also made sure that I do the following:

I have also done the following
$ sudo vim /etc/postgresql/9.3/main/postgresql.conf
...
shared_preload_libraries = 'schema_triggers.so'

$ sudo service postgresql restart # restart postgres
NOTICE:  database "contrib_regression" does not exist, skipping
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test test_setup               ... ok
test test_ddl_triggers        ... FAILED
test test/CDB_CartodbfyTableTest ... ok
test test/CDB_DigitSeparatorTest ... ok
test test/CDB_DistinctMeasureTest ... ok
test test/CDB_DistTypeTest    ... ok
test test/CDB_EqualIntervalBinsTest ... ok
test test/CDB_HeadsTailsBinsTest ... ok
test test/CDB_HexagonTest     ... ok
test test/CDB_JenksBinsTest   ... ok
test test/CDB_MathTest        ... ok
test test/CDB_QuantileBinsTest ... ok
test test/CDB_QueryStatementsTest ... ok
test test/CDB_QueryTablesTest ... FAILED
test test/CDB_QuotaTest       ... ok
test test/CDB_StatsTest       ... ok
test test/CDB_TransformToWebmercatorTest ... ok
test test/CDB_UserTablesTest  ... ok
test test/CDB_XYZ_ExtentTest  ... ok
# 
#  2 of 19 tests failed. 

Any help will be appreciated as I have redone the steps a number of times, but still get the same error

**Comment by danseely** [comment]
One thing that had me stuck on this was that I ended up having to restart postgresql _twice_. Sounds crazy, but try restarting again.

**Comment by sindile** [comment]
Thanks for the comment - have tried that but still no luck. Will try to proceed and see what happens.
