### ISSUE TITLE
Error while installing Windshaft-cartodb

### ISSUE THREAD

**Issue by mfarook** [danseely/cartodb-install#2]
Hi,

I am setting cartoDB locally in ubuntu 12.04 by following https://github.com/danseely/cartodb-install/blob/master/DEV-INSTALLATION.md. And while installing Windshaft-cartodb there are some errors logged in npm-debug.log file. And below is the error in the log file 

42454 info postuninstall windshaft@1.0.1
42455 error mapnik@1.4.15-cdb2 install: `node-pre-gyp install --fallback-to-build`
42455 error Exit status 1
42456 error Failed at the mapnik@1.4.15-cdb2 install script.
42456 error This is most likely a problem with the mapnik package,
42456 error not with npm itself.
42456 error Tell the author that this fails on your system:
42456 error     node-pre-gyp install --fallback-to-build
42456 error You can get their info via:
42456 error     npm owner ls mapnik
42456 error There is likely additional logging output above.
42457 error System Linux 3.2.0-23-generic-pae
42458 error command "/usr/bin/node" "/usr/bin/npm" "install"
42459 error cwd /home/user/Windshaft-cartodb
42460 error node -v v0.10.26
42461 error npm -v 1.4.3
42462 error code ELIFECYCLE
42463 verbose exit [ 1, true ]

Any help regarding what makes this error and how to solve would be appreciated.

**Comment by danseely** [comment]
Questions:
- did these logs propagate after you ran `npm install` in the Windshaft directory?
- During install, did you get any errors in the terminal?

**Comment by mfarook** [comment]
Yes these logs were after running npm install in the Windshaft directory.
Yes the same errors were there in the terminal also.

**Comment by danseely** [comment]
Might be a version issue? Take a look at [this thread](https://groups.google.com/forum/#!searchin/cartodb/windshaft$20error$20mapnik/cartodb/PHoQ7LamnV8/kmfPfvwc1BsJ).

**Comment by mfarook** [comment]
Will Mapnik 2.2 creates a problem? I am using Mapnik 2.2.

**Comment by danseely** [comment]
According to the Windshaft-cartodb docs, 2.2 is supported. I'm not quite sure what's causing your issue, I'd suggest [creating a question on the Google Group](https://groups.google.com/forum/#!forum/cartodb). Sorry!

**Comment by mfarook** [comment]
Well Okay. Anyway thanks for your time.

**Comment by danseely** [comment]
Good luck, I've had great luck with the team on the forum.
